In [1]:
import tensorflow as tf

In [2]:
graph1 = tf.Graph()

In [3]:
with graph1.as_default():
    a = tf.constant([2], name = "constant_a")
    b = tf.constant([3], name = "constant_b")

In [4]:
a

<tf.Tensor 'constant_a:0' shape=(1,) dtype=int32>

In [5]:
b

<tf.Tensor 'constant_b:0' shape=(1,) dtype=int32>

In [9]:
sess = tf.Session(graph = graph1)
result = sess.run(a)
print(result)
sess.close()

[2]


In [10]:
with graph1.as_default():
    c = tf.add(a,b)

In [11]:
c

<tf.Tensor 'Add:0' shape=(1,) dtype=int32>

In [14]:
sess = tf.Session(graph = graph1)
result = sess.run(c)
print(result)
sess.close()

[5]


In [17]:
with tf.Session(graph = graph1) as sess:
    result = sess.run(a)
    print(result)

[2]


In [18]:
graph2 = tf.Graph()
with graph2.as_default():
    Scalar = tf.constant(2)
    Vector = tf.constant([5,6,2])
    Matrix = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Tensor = tf.constant( [ [[1,2,3],[2,3,4],[3,4,5]] , [[4,5,6],[5,6,7],[6,7,8]] , [[7,8,9],[8,9,10],[9,10,11]] ] )
with tf.Session(graph = graph2) as sess:
    result = sess.run(Scalar)
    print ("Scalar (1 entry):\n %s \n" % result)
    result = sess.run(Vector)
    print ("Vector (3 entries) :\n %s \n" % result)
    result = sess.run(Matrix)
    print ("Matrix (3x3 entries):\n %s \n" % result)
    result = sess.run(Tensor)
    print ("Tensor (3x3x3 entries) :\n %s \n" % result)

Scalar (1 entry):
 2 

Vector (3 entries) :
 [5 6 2] 

Matrix (3x3 entries):
 [[1 2 3]
 [2 3 4]
 [3 4 5]] 

Tensor (3x3x3 entries) :
 [[[ 1  2  3]
  [ 2  3  4]
  [ 3  4  5]]

 [[ 4  5  6]
  [ 5  6  7]
  [ 6  7  8]]

 [[ 7  8  9]
  [ 8  9 10]
  [ 9 10 11]]] 



In [24]:
Matrix.shape

TensorShape([Dimension(3), Dimension(3)])

In [37]:
graph3 = tf.Graph()
with graph3.as_default():
    Matrix_one = tf.constant([[1,2,3],[2,3,4],[3,4,5]])
    Matrix_two = tf.constant([[2,2,2],[2,2,2],[2,2,2]])
    add_1_operation = tf.matmul(Matrix_one, Matrix_two)
    add_2_operation = Matrix_one * Matrix_two
with tf.Session(graph = graph3) as sess:
    result = sess.run(Matrix_one)
    print ("Mat 1")
    print(result)
    result = sess.run(Matrix_two)
    print ("Mat 2")
    print(result)

Mat 1
[[1 2 3]
 [2 3 4]
 [3 4 5]]
Mat 2
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [36]:
with tf.Session(graph = graph3) as sess:
    result = sess.run(add_1_operation)
    print ("Defined using tensorflow function :")
    print(result)
    result = sess.run(add_2_operation)
    print ("Defined using normal expressions :")
    print(result)

Defined using tensorflow function :
[[12 12 12]
 [18 18 18]
 [24 24 24]]
Defined using normal expressions :
[[ 2  4  6]
 [ 4  6  8]
 [ 6  8 10]]
